openapi: 3.0.0
info:
  title: Exsample API
  description: サンプル API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    
tags:
  - name: "users"
    description: "ユーザーの操作"
  
paths:
  '/api/v1/users/{user_id}':
    $ref: "./paths/user.yaml"