openapi: 3.0.0
info:
  title: Routine Manage API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    
tags:
  - name: "user"
    description: "ユーザーの操作"
  - name: "rqoutine"
    description: "ルーティンの操作"
paths:
  '/api/users/{user_id}':
    $ref: "./paths/user.yaml"
# Routin API Endpoint
  '/api/routine/':
    $ref: "./paths/routines.yaml"
  '/api/routine/{routine_id}':
    $ref: "./paths/routine.yaml"